id: medcom.fhir.dk.xdsdocuments
canonical: https://medcomfhir.dk/ig/xdsdocuments
name: Metadata profiles for MedCom XDS Documents for national sharing
title: MedCom Documents XDS Metadata profiles IG 
description: MedCom Documents XDS Metadata profiles IG 
status: draft # draft | active | retired | unknown
version: 1.0.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2023+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: MedCom
  url: https://medcom.dk/
  email: fhir@medcom.dk

dependencies:
  hl7.fhir.dk.core: 3.3.0
  medcom.fhir.dk.core: 2.4.0
  medcom.fhir.dk.coredocument: dev #1.0.0
  medcom.fhir.dk.xdsmetadata: dev #1.0.0

parameters:  
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true

menu:
  Home: index.html
  Profiles: profiles.html
  Extensions: extensions.html
  Artifacts: artifacts.html
  
instanceOptions:
  manualSliceOrdering: true # true | false
